[run]
silent = true

[test]
root = "."
preload = ["./tests/preload.ts"]

# Set timeout to 0 to disable it completely across all tests
timeout = 0
pathIgnorePatterns = [
  "ALL/**",
  "ALL_REBUILT/**",
  "logs/**",
  "dist/**",
  "**/types/**",
  "**/utils/**",
]

# Coverage configuration
coverage = true
coverageReporter = ["text"]
coverageDir = "./coverage"
coverageThreshold = { lines = 0.85, functions = 0.90 }
coverageSkipTestFiles = true
coverageIgnoreSourcemaps = false
coveragePathIgnorePatterns = [
  # Untestable command line entry points and export files
  "**/*.bin.ts",
  "**/index*",

  # Test files and folders
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/*.e2e.ts",

  # Configuration files
  "*.config.js",
  "*.config.ts",
  "vite.config.*",

  # Build output & Generated code
  "dist/**",
  "ALL/**",
  "ALL_REBUILT/**",
  "**/node_modules/**",

  # Utilities that don't need testing
  "**/types/**",
  "**/utils/**",
  "**/tests/preload.*",
]
