/**
 * @module clean
 * @file FILE-PATH: clean.ts
 *
 * Single responsibility: remove generated/build output across the
 * whole workspace — `bun run clean`. Bun-native (`fs.rm`), no external
 * dependency needed. Safe to re-run; missing paths are silently
 * skipped via `force: true`.
 */

const TARGETS = [
    // Root CLI build output
    'dist',
    // Pendex's own compile/split output, when run against this repo itself
    'ALL',
    'ALL_REBUILT',
    // Per-package build/coverage output
    'packages/home/dist',
    'packages/color/dist',
    'packages/theme/dist',
    'packages/core/dist',
    'packages/compile/dist',
    'packages/split/dist',
    'coverage',
    // TypeScript project-reference build info
    'packages/home/node_modules/.tmp',
];

for (const target of TARGETS) {
    await Bun.$`rm -rf ${target}`.quiet().catch(() => {});
}

// Generated API reference (regenerated by `bun run docs:api`) — clear its
// contents but keep the directory (and its .gitkeep) so a fresh checkout
// still has somewhere for typedoc to write into.
await Bun.$`find packages/home/public/docs/api -mindepth 1 ! -name .gitkeep -delete`
    .quiet()
    .catch(() => {});

console.log(`Cleaned ${TARGETS.length} build output paths.`);
